[graph]
all-features = true

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
]

[advisories]
version = 2
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
